#Server:
#    port:8081
#Spring:
#    redis:
#        host: 127.0.0.1
#        password: null
#        port: 6379
#        pool:
#            max-idle: 100
#            min-idle: 1
#            max-active: 1000
#            max-wait: -1
#logging:
#    path: ./logs/
#    level:
#        root: DEBUG


#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2
#
#  jpa:
#    hibernate:
#      ddl-auto: none



#server:
#  port: 8080
#
#security:
#  oauth2:
#    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
#    client:
#      client-id: clientapp
#      client-secret: 112233
#    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
#    resource:
#      filter-order: 3
#      token-info-uri: http://127.0.0.1:8080/oauth/check_token # 获得 Token 信息的 URL
#    # 访问令牌获取 URL，自定义的
#      access-token-uri: http://127.0.0.1:8080/oauth/token
